In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('exp2.csv.csv')
n_row = df.shape[0]

li = []
for i in range(n_row):
    li.append(1)

df.insert(0,"X0", li, True)  
print(df)


   X0  X1  X2    Y
0   1   5  45  460
1   1   3  40  232
2   1   3  30  315
3   1   2  36  178


In [ ]:
main_matrix = df.to_numpy()

In [ ]:
print(main_matrix)


[[  1   5  45 460]
 [  1   3  40 232]
 [  1   3  30 315]
 [  1   2  36 178]]


In [ ]:
n_col = df.shape[1]

result = np.hsplit(main_matrix, [n_col-1,n_col]) 
X = result[0]
Y = result[1]

print(X)
print(Y)

[[ 1  5 45]
 [ 1  3 40]
 [ 1  3 30]
 [ 1  2 36]]
[[460]
 [232]
 [315]
 [178]]


In [ ]:
X_T = X.transpose()
print(X_T)

[[ 1  1  1  1]
 [ 5  3  3  2]
 [45 40 30 36]]


In [ ]:
X_T_X = np.matmul(X_T,X)
print(X_T_X)

[[   4   13  151]
 [  13   47  507]
 [ 151  507 5821]]


In [ ]:
inv = np.linalg.inv(X_T_X)
print(inv)

[[13.35864297  0.71405493 -0.40872375]
 [ 0.71405493  0.3901454  -0.05250404]
 [-0.40872375 -0.05250404  0.01534733]]


In [ ]:
inv_T = np.matmul(inv, X_T)
print(inv_T)

[[-1.46365105 -0.84814216  3.23909532  0.0726979 ]
 [ 0.30210016 -0.21567044  0.30936995 -0.39579968]
 [ 0.01938611  0.04765751 -0.10581583  0.03877221]]


In [ ]:
answer = np.matmul(inv_T, Y)
print(answer)

[[163.20678514]
 [115.92972536]
 [ -6.45638126]]


In [ ]:
temp = ""
for i in range(1,n_col-1):
  if answer[i][0]<0:
    temp += " - "+str(-answer[i][0])+" X"+str(i)
  else:
    temp += " + "+str(answer[i][0])+" X"+str(i)
print("Y = "+ str(answer[0][0])+temp)


Y = 163.20678513731286 + 115.92972536348917 X1 - 6.45638126009684 X2
