In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('exp3.csv')
m = df.shape[0]
n = df.shape[1]
n = n-1

print(df)
print("\n---------------------------")
li = []
for i in range(m):
    li.append(1)

df.insert(0,"X0", li, True)
print(df)

print("\nNo. of Samples:",m)
print("No. of features:",n)

      P     C     M  Y
0  0.98  0.97  0.91  1
1  0.87  0.91  0.90  1
2  0.84  0.85  0.89  0
3  0.88  0.86  0.87  0
4  0.89  0.91  0.92  1

---------------------------
   X0     P     C     M  Y
0   1  0.98  0.97  0.91  1
1   1  0.87  0.91  0.90  1
2   1  0.84  0.85  0.89  0
3   1  0.88  0.86  0.87  0
4   1  0.89  0.91  0.92  1

No. of Samples: 5
No. of features: 3


In [ ]:
theta_T = [-1, 0.7, 1, 0.5]
print(theta_T)

[-1, 0.7, 1, 0.5]


In [ ]:
main_matrix = df.to_numpy()

In [ ]:
n_col = df.shape[1]
# print(n_col)

result = np.hsplit(main_matrix,[n_col-1,n_col]) 

X = result[0]
Y = result[1]

print("X=\n",X)
print("\nY=\n",Y)

X=
 [[1.   0.98 0.97 0.91]
 [1.   0.87 0.91 0.9 ]
 [1.   0.84 0.85 0.89]
 [1.   0.88 0.86 0.87]
 [1.   0.89 0.91 0.92]]

Y=
 [[1.]
 [1.]
 [0.]
 [0.]
 [1.]]


In [ ]:
import math
def h_theta_x(X):
  X_T = X.transpose()
  theta_T_X = np.matmul(theta_T,X_T)
  return 1/(1+math.exp(-theta_T_X))

In [ ]:
#Calculation of J theta
import math
J_theta=0
for i in range(m):
  temp = h_theta_x(X[i])
  # print(temp)
  J_theta = J_theta + (-Y[i] * math.log(temp,10)-((1-Y[i])*math.log(1-temp,10)))

J_theta = 1/m * J_theta
print("J theta =",J_theta[0])

J theta = 0.29527913094328645


In [ ]:
#Updating the parameters
alpha=0.3
for k in range(2):
  print("\nEPOCH =",k+1)
  for j in range(len(theta_T)):
    temp=0
    for i in range(m):
      temp = temp + (h_theta_x(X[i])-Y[i])*X[i][j]
    # print(temp)
    theta_T[j] = theta_T[j] - (alpha *temp[0])
  
  print("Theta =",theta_T)

  #Calculation of J theta
  J_theta=0
  for i in range(m):
    temp = h_theta_x(X[i])
    # print(temp)
    J_theta = J_theta + (-Y[i] * math.log(temp,10)-((1-Y[i])*math.log(1-temp,10)))

  J_theta = 1/m * J_theta
  print("J theta =",J_theta[0])


EPOCH = 1
Theta = [-1.1882691871314535, 0.6023017847427438, 0.9347842958157393, 0.4372275838465639]
J theta = 0.28213578106612364

EPOCH = 2
Theta = [-1.2506237497758774, 0.5841073505364456, 0.9292388459898026, 0.41789210685321154]
J theta = 0.28102216238292205
